# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-12-21 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20160729_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='group',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
