# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 10:26
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20161223_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
